### ISSUE TITLE
How can I access the Unsafe or Cleaner class from libcore using this library

### ISSUE THREAD

**Issue by saila-lopa** [JakeWharton/libcore-dex#1]
I can't find the Unsafe or Cleaner class in the class list page. But libcore directory does define Unsafe and Cleaner class in one of the packages. Or can you help on how to build the libcore like you did including those classes ?

**Comment by JakeWharton** [comment]
This is only the `libcore/dex/` library (which has since moved to `dalvik/dx/`). The `Unsafe` and `Cleaner` classes sounds like you're referring to ones in OpenJDK which are not part of this library.

**Comment by saila-lopa** [comment]
The following directory has the classes I need
https://android.googlesource.com/platform/libcore/+/master/ojluni/src/main/java/sun/misc/

Can you help me on how can I use this 'ojluni' package in my android application? 
Thanks.
